const TRANSACTION_TOKEN_SECRET = "This_S3CR3T_MustLieHere4the_3t3RN!7Y";
const PERSISTENT_TOKEN_SECRET = "TH15_I5_TH3_53CR3T_Y0U_C4NN07_GU3$$_&_A150_7H1S_MU5T_B3_L0NG3R_TH4N_0THER";
const TRANSACTION_TOKEN_DURATION = "50d";
const PERSISTENT_TOKEN_DEFAULT_DURATION = "1d";
const PERSISTENT_TOKEN_EXTENDED_DURATION = "7d";

module.exports = {
  TRANSACTION_TOKEN_SECRET,
  PERSISTENT_TOKEN_SECRET,
  TRANSACTION_TOKEN_DURATION,
  PERSISTENT_TOKEN_DEFAULT_DURATION,
  PERSISTENT_TOKEN_EXTENDED_DURATION,
};
